FROM node:20-bookworm

# Install system dependencies required by Chromium
RUN apt-get update && apt-get install -y \
    ca-certificates \
    fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libxshmfence1 \
    xdg-utils \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Prevent Puppeteer from downloading Chromium again
ENV PUPPETEER_SKIP_DOWNLOAD=true

# Puppeteer Chromium path (comes with puppeteer package)
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

# Install Chromium
RUN apt-get update && apt-get install -y chromium \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

# Install dev hot reload tool
RUN npm install -g ts-node-dev

COPY . .

CMD ["sh", "-c", "ts-node-dev --respawn --transpile-only --poll src/server.ts"]
